---
- name: Debug Play
  hosts: all
  gather_facts: false

  tasks:
    - name: Display encrypted values
      ansible.builtin.debug:
        msg:
          - "API Key: {{ api_key }}"
          - "DB Password: {{ db_credentials.password }}"
          - "User Password: {{ user_password }} / {{ user_password | password_hash('sha512', 'salt17yui29') }}"
